name: Release Please

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: "release-please"
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: "publish to PyPI"
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created || github.event_name == 'workflow_dispatch' }}
    environment:
      name: pypi
      url: https://pypi.org/p/lastlint
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.x"
      - run: pip install build && python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
